---
deployment:
  tasks:
    - export DEPLOYPATH=/home/warwickh/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp assets/style.css $DEPLOYPATH/assets
    - /bin/cp assets/scripts/jquery.css $DEPLOYPATH/assets/scripts
    - /bin/cp assets/scripts/script.css $DEPLOYPATH/assets/scripts
    - /bin/cp assets/imgs $DEPLOYPATH/assets/imgs
