---
deployment:
  tasks:
    - export DEPLOYPATH=/home/warwickh/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp assets/style.css $DEPLOYPATH
    - /bin/cp assets/scripts/jquery.css $DEPLOYPATH
    - /bin/cp assets/scripts/script.css $DEPLOYPATH
    - /bin/cp assets/imgs $DEPLOYPATH
